#!/usr/bin/env bash
datasets0=(  
    "/data/megastore/SHARE/TTS/VoiceClone/NTTS/NTTS"
    "/data/megastore/SHARE/TTS/VoiceClone/ENTTS/ENTTS"
    "/data/megastore/SHARE/TTS/VoiceClone/LTTS/LTTS"
    "/data/megastore/SHARE/TTS/VoiceClone/MSTTS_EN/MSTTS_EN"
    "/data/megastore/SHARE/TTS/VoiceClone/MSTTS_CN/MSTTS_CN"
    "/data/megastore/SHARE/TTS/VoiceClone/ENTTS_LibriTTS/ENTTS_LibriTTS"
    "/data/megastore/SHARE/TTS/VoiceClone/ASR_KeSpeech/ASR_KeSpeech"
    "/data/megastore/SHARE/TTS/VoiceClone/ASR_WenetSpeech/ASR_WenetSpeech"
    "/data/megastore/SHARE/TTS/VoiceClone/Mandarin/Mandarin"
    "/data/megastore/SHARE/TTS/VoiceClone/ASR_CN5k/ASR_CN5k"
    "/data/megastore/SHARE/TTS/VoiceClone/ManEngMix/ManEngMix"
    "/data/megastore/SHARE/TTS/VoiceClone/ASR_MLS/ASR_MLS"
    "/data/megastore/SHARE/TTS/VoiceClone/Conversation/Conversation"
    "/data/megastore/SHARE/TTS/VoiceClone/ASR_LibriHeavy/ASR_LibriHeavy"
    "/data/megastore/SHARE/TTS/VoiceClone/ASR_Refine/ASR_Refine"
    "/data/megastore/SHARE/TTS/VoiceClone/ASR_GigaSpeech/ASR_GigaSpeech"
)

datasets1=(
    "/data/megastore/SHARE/TTS/VoiceClone2/Live_LuoYonghao/Live_LuoYonghao"
    "/data/megastore/SHARE/TTS/VoiceClone2/TTS_unlab/TTS_unlab"
    "/data/megastore/SHARE/TTS/VoiceClone2/20240122/20240122"
    "/data/megastore/SHARE/TTS/VoiceClone2/20241014/20241014"
    "/data/megastore/SHARE/TTS/VoiceClone2/20241014_en/20241014_en"
    "/data/megastore/SHARE/TTS/VoiceClone2/20241021/20241021"
    "/data/megastore/SHARE/TTS/VoiceClone2/20241021_en/20241021_en"
    "/data/megastore/SHARE/TTS/VoiceClone2/HighQuality16/HighQuality16"
    "/data/megastore/SHARE/TTS/VoiceClone2/HighQuality16_en/HighQuality16_en"

    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240129/20240129"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240205/20240205"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240205_1/20240205_1"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240212/20240212"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240212_1/20240212_1"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240219/20240219"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240226/20240226"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240304/20240304"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240304_en/20240304_en"    
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240311/20240311"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240311_en/20240311_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240318/20240318"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240318_en/20240318_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240930/20240930"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240930_en/20240930_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20241007/20241007"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20241007_en/20241007_en"

    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality1/HighQuality1"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality1_en/HighQuality1_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality2/HighQuality2"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality3_en/HighQuality3_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality4/HighQuality4"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality4_en/HighQuality4_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality5/HighQuality5"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality5_en/HighQuality5_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality6/HighQuality6"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality6_en/HighQuality6_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality7/HighQuality7"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality7_en/HighQuality7_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality8/HighQuality8"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality8_en/HighQuality8_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality9/HighQuality9"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality9_en/HighQuality9_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality11/HighQuality11"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality11_en/HighQuality11_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality31/HighQuality31"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality31_en/HighQuality31_en"    
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality33/HighQuality33"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality33_en/HighQuality33_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality34/HighQuality34"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality34_en/HighQuality34_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality35/HighQuality35"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality35_en/HighQuality35_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality36/HighQuality36"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality36_en/HighQuality36_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality37/HighQuality37"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality37_en/HighQuality37_en"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality38/HighQuality38"
    "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality38_en/HighQuality38_en"
)


datasets2=( 
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/MidQuality1/MidQuality1"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/MidQuality1_en/MidQuality1_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality10/HighQuality10"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality10_en/HighQuality10_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality12/HighQuality12"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality12_en/HighQuality12_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality13/HighQuality13"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality13_en/HighQuality13_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality14/HighQuality14"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality14_en/HighQuality14_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality15/HighQuality15"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality15_en/HighQuality15_en"

    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241028/20241028"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241028_en/20241028_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241104/20241104"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241104_en/20241104_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241111/20241111"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241111_en/20241111_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241118/20241118"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241118_en/20241118_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241125/20241125"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241125_en/20241125_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality17/HighQuality17"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality17_en/HighQuality17_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality18/HighQuality18"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality18_en/HighQuality18_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality19/HighQuality19"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality19_en/HighQuality19_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality20/HighQuality20"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality20_en/HighQuality20_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality21/HighQuality21"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality21_en/HighQuality21_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality22/HighQuality22"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality22_en/HighQuality22_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality22_1/HighQuality22_1"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality22_1_en/HighQuality22_1_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality23/HighQuality23"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality23_en/HighQuality23_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality24/HighQuality24"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality24_en/HighQuality24_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality25/HighQuality25"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality25_en/HighQuality25_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality26/HighQuality26"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality26_en/HighQuality26_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality27/HighQuality27"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality27_en/HighQuality27_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality28/HighQuality28"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality28_en/HighQuality28_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality29/HighQuality29"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality29_en/HighQuality29_en"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality30/HighQuality30"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality30_en/HighQuality30_en"    
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality32/HighQuality32"
    "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality32_en/HighQuality32_en"
)


for dataset in "${datasets2[@]}"; do
  sub=$(basename "$dataset")
  echo "run $sub"

  python infer_kaldidata.py   \
     --wav_scp $dataset/wav.scp  \
     --batch_size 32    \
     --log_dir $dataset  \
     --vllm_model_dir ./yuekai/Fun-ASR-Nano-2512-vllm \
     --multiprocess --num_processes 8 --gpu_list 0,1,2,3,4,5,6,7

done